name: Create Jira Issue from GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get Active Sprint ID
        id: get-sprint
        env:
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          BOARD_ID=562 # <-- replace with your board ID
          RESPONSE=$(curl -s -u "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" \
            -H "Accept: application/json" \
            "https://adsvc.atlassian.net/rest/agile/1.0/board/$BOARD_ID/sprint?state=active")
          SPRINT_ID=$(echo "$RESPONSE" | jq '.values[0].id')
          echo "SPRINT_ID=$SPRINT_ID" >> $GITHUB_ENV
      
      - name: Create Jira Issue via REST API
        env:
          JIRA_BASE_URL: https://adsvc.atlassian.net
          JIRA_PROJECT_KEY: FAS
          JIRA_EPIC_KEY: FAS-1
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          SPRINT_ID: ${{ env.SPRINT_ID }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          # Escape double quotes and backslashes in the issue body for JSON
          SAFE_BODY=$(echo "$ISSUE_BODY" | sed 's/\\/\\\\/g; s/"/\\"/g')
          DESCRIPTION_JSON="{\"type\":\"doc\",\"version\":1,\"content\":[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"$SAFE_BODY\"}]}]}"
          curl -X POST \
            -H "Content-Type: application/json" \
            -u "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" \
            --data "{
              \"fields\": {
                \"project\": { \"key\": \"$JIRA_PROJECT_KEY\" },
                \"summary\": \"$ISSUE_TITLE\",
                \"description\": $DESCRIPTION_JSON,
                \"issuetype\": { \"name\": \"Task\" },
                \"customfield_10014\": \"$JIRA_EPIC_KEY\"
                \"customfield_10020\": $SPRINT_ID
              }
            }" \
            "$JIRA_BASE_URL/rest/api/3/issue"
