name: Create Jira Issue from GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue via REST API
        env:
          JIRA_BASE_URL: https://adsvc.atlassian.net
          JIRA_PROJECT_KEY: FAS
          JIRA_EPIC_KEY: FAS-1
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          curl -X POST \
            -H "Content-Type: application/json" \
            -u "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" \
            --data "{
              \"fields\": {
                \"project\": { \"key\": \"$JIRA_PROJECT_KEY\" },
                \"summary\": \"$ISSUE_TITLE\",
                \"description\": \"$ISSUE_BODY\",
                \"issuetype\": { \"name\": \"Task\" },
                \"customfield_10014\": \"$JIRA_EPIC_KEY\"
              }
            }" \
            "$JIRA_BASE_URL/rest/api/3/issue"

